/**
 * Signal-related type definitions for the Isagi Engine Signal Bot.
 * Defines raw and formatted signal structures, ticket details, and slippage.
 */

import type { Candle } from './candle.js';
import type { ZoneClassification } from './zone.js';

/** Raw signal generated by the Signal Engine FSM */
export interface RawSignal {
  id: string;
  timestamp: string;
  /** Instrument is optional for backward-compatible library callers; live FSM signals always set it. */
  instrument?: 'XAUUSD' | 'BTCUSD';
  direction: 'long' | 'short';
  entryPrice: number;
  liquidityZoneLevel: number;
  structuralWindowUpper: number;
  structuralWindowLower: number;
  rejectionCandleType:
    | 'shooting_star'
    | 'hammer'
    | 'bearish_engulfing'
    | 'bullish_engulfing';
  expansionCandles: Candle[];
  retracementCandles: Candle[];
  observationCandles: Candle[];
}

/** Formatted signal output with full position details */
export interface FormattedSignal {
  id: string;
  timestamp: string;
  instrument: 'XAUUSD' | 'BTCUSD';
  direction: 'long' | 'short';
  entryPrice: number;
  stopLoss: number;
  ticket1: TicketDetail;
  ticket2: TicketDetail;
  zoneClassification: ZoneClassification;
  riskAmount: number;
  rUnit: number;
  reasoning: string;
  slippage: SlippageResult;
  breakevenTrigger: string;
  trailingStopGuidance: string;
}

/** Individual ticket detail within a split position */
export interface TicketDetail {
  label: string;
  positionSizePercent: number;
  entryPrice: number;
  stopLoss: number;
  takeProfit: number;
}

/** Result of the slippage simulation for a signal */
export interface SlippageResult {
  applied: boolean;
  originalEntry: number;
  adjustedEntry: number;
  slippagePips: number;
}
