/**
 * One-shot test script: sends a clearly labeled BTC/USD example to Telegram.
 * This verifies Telegram delivery only; it is not generated by the live engine.
 * Usage: TELEGRAM_BOT_TOKEN=... TELEGRAM_CHAT_ID=... npx tsx scripts/send-test-signal.ts
 */

const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN ?? '';
const CHAT_ID = process.env.TELEGRAM_CHAT_ID ?? '';

const message = `⚠️ <b>TEST ONLY — NOT A REAL TRADING SIGNAL</b>

<b>Purpose:</b> Verify BTC/USD Telegram delivery. Do not trade from this message.

<b>Example:</b> BTC/USD LONG

<b>Entry:</b> 63940.00
<b>Stop Loss:</b> 63740.00
<b>TP1:</b> 64240.00 (Safety Lock 45%)
<b>TP2:</b> 64540.00 (Runner 55%)

<b>Zone:</b> Expansion Zone (3.0R)
<b>Risk:</b> Example only
<b>R-Unit:</b> 200.00 price units

<b>Reasoning:</b> Synthetic BTC/USD test message used only to verify Telegram delivery and instrument labeling.

<b>Management:</b>
• This is not a live setup
• Do not place a trade from this message
• Live bot remains signal-only and never executes orders`;

async function main() {
  if (!BOT_TOKEN || !CHAT_ID) {
    console.error('❌ Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID before running this test.');
    process.exitCode = 1;
    return;
  }

  const url = `https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`;

  const body = JSON.stringify({
    chat_id: CHAT_ID,
    text: message,
    parse_mode: 'HTML',
  });

  console.log('Sending test signal to Telegram...');
  console.log(`Chat ID: ${CHAT_ID}`);
  console.log('---');

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body,
    });

    const data = await response.json();

    if (response.ok && data.ok) {
      console.log('✅ Message sent successfully!');
      console.log(`Message ID: ${data.result.message_id}`);
      console.log(`Date: ${new Date(data.result.date * 1000).toISOString()}`);
    } else {
      console.error('❌ Failed to send message.');
      console.error(`Status: ${response.status} ${response.statusText}`);
      console.error('Response:', JSON.stringify(data, null, 2));
    }
  } catch (error) {
    console.error('❌ Error sending message:', error);
  }
}

main();
